services:
  backend:
    build:
      context: ../../backend
      dockerfile: docker/Dockerfile
    container_name: e2e_backend
    ports:
      - "8080:8080"
    env_file:
      - ../../backend/config/env.development
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=sampleuser
      - DB_PASSWORD=samplepass
      - DB_NAME=sampledb
    networks:
      - e2e-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: ../../frontend
      dockerfile: docker/Dockerfile.dev
    container_name: e2e_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:8080
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    networks:
      - e2e-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  db:
    image: postgres:15
    container_name: e2e_pg
    environment:
      POSTGRES_USER: sampleuser
      POSTGRES_PASSWORD: samplepass
      POSTGRES_DB: sampledb
    ports:
      - "15435:5432"  # Different port to avoid conflicts
    volumes:
      - e2e_pgdata:/var/lib/postgresql/data
      - ../../backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - e2e-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sampleuser -d sampledb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  e2e-tests:
    build:
      context: ../../frontend
      dockerfile: docker/Dockerfile.e2e
    container_name: e2e_playwright
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    environment:
      - PLAYWRIGHT_BASE_URL=http://frontend:5173
      - CI=true
    volumes:
      - ../../frontend/tests:/app/tests
      - ../../frontend/playwright.config.js:/app/playwright.config.js
      - e2e_reports:/app/playwright-report
      - e2e_results:/app/test-results
    networks:
      - e2e-network
    profiles:
      - e2e

volumes:
  e2e_pgdata:
  e2e_reports:
  e2e_results:

networks:
  e2e-network:
    driver: bridge